# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='order',
        ),
    ]
