# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170714_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comment',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
