# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_user_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-avatar.svg', upload_to='avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1500, verbose_name='presentation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ratio'),
        ),
    ]
