# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170727_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='birth date'),
        ),
    ]
