# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20170729_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-avatar.svg', upload_to='media/avatars/', verbose_name='avatar'),
        ),
    ]
