# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20170730_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/default-avatar.png', upload_to='media/avatars/', verbose_name='avatar'),
        ),
    ]
