# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20170807_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='TripItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('average_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_qty', models.IntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tripItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TripItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
