# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20170807_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='orderAmount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', max_length=1500, verbose_name='orderDescription'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'refused'), (1, 'pending'), (2, 'accepted'), (3, 'running'), (4, 'honored')], default=1, verbose_name='orderStatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='orderItemAmount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='orderItemQty'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='amount_limit',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='tripMaxAmount'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city_end',
            field=models.CharField(max_length=100, verbose_name='tripCityEnd'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city_start',
            field=models.CharField(max_length=100, verbose_name='tripCityStart'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='comment',
            field=models.TextField(default='', max_length=1500, verbose_name='tripDescription'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(verbose_name='tripDate'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='participants_limit',
            field=models.IntegerField(default=0, verbose_name='tripMaxParticipants'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='average_qty',
            field=models.IntegerField(default=1, verbose_name='tripItemAVGQty'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='average_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='tripItemAVGValue'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='description',
            field=models.TextField(max_length=500, verbose_name='tripItemDescription'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='title',
            field=models.TextField(max_length=150, verbose_name='tripItemTitle'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
    ]
