# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20170807_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='average_qty',
            field=models.IntegerField(blank=True, default=0, verbose_name='tripItemAVGQty'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='average_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='tripItemAVGValue'),
        ),
    ]
